# Datadog Agent with Logs, APM, Processes, and System Probe enabled
# with specific configurations to work on OpenShift 4.
# When installing the chart, install onto a non-default namespace with
# `helm install --namespace <your_ns>` due to existing SecurityContextConstraints
# on the default namespace. For more details about setting appropriate security
# constraints, see https://docs.datadoghq.com/integrations/openshift/ and
# https://www.datadoghq.com/blog/openshift-monitoring-with-datadog/

targetSystem: "linux"
datadog:
  # apiKey: <DATADOG_API_KEY>
  # appKey: <DATADOG_APP_KEY>
  # If not using secrets, then use apiKey and appKey instead
  apiKeyExistingSecret: <DATADOG_API_KEY_SECRET>
  appKeyExistingSecret: <DATADOG_APP_KEY_SECRET>
  clusterName: <CLUSTER_NAME>
  tags: []
  criSocketPath: /var/run/crio/crio.sock
  # datadog.kubelet.tlsVerify should be `false` to establish communication with the kubelet
  kubelet:
    tlsVerify: "false"
  confd:
    cri.yaml: |-
      init_config:
      instances:
        - collect_disk: true
  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: true
  apm:
    enabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
